# 1.1.	You are given with a list of integer elements. Make a new list which will store square of elements of previous list.

In [8]:
#ls = [1,2,3]
ls = list(map(int,input("enter your no of list:").split()))
ls_1 =[]
for i in ls:
    #ls_1.append(i*i)
    ls_1.append(i**2)
print(ls_1)

enter your no of list:1 2 3 4
[1, 4, 9, 16]


# 2.	From a list containing ints, strings and floats, make three lists to store them separately. 

In [11]:
ls = [1, 2,'a','b','c',1.3,1.5,3.3]
a =[]
b =[]
c=[]
for i in ls:
    if type(i) == int:
        a.append(i)
    elif type(i) == str:
        b.append(i)
    elif type(i) == float:
        c.append(i)
print(a)
print(b)
print(c)
        


[1, 2]
['a', 'b', 'c']
[1.3, 1.5, 3.3]


# 3.	Print the pattern
1
1 2 
1 2 3
1 2 3 4
1 2 3 4 5


In [25]:
n = int(input("enter your no of rows :"))
for i in range(n+1):
    for j in range(1,i+1):
        print(j,end=" ")
    print(" ")

enter your no of rows :5
 
1  
1 2  
1 2 3  
1 2 3 4  
1 2 3 4 5  


# 4.	Accept data in two 3*3  matrix and calculate the sum of the matrices.

In [29]:
a = [[1,2,3],[3,4,5],[5,6,7]]
b = [[3,4,5],[8,9,0],[4,3,6]]
c = [[0,0,0],[0,0,0],[0,0,0]]
for i in range(len(a)):
    for j in range(len(b[0])):
        c[i][j] = a[i][j] + b[i][j]
print(c)
        
        
        

[[4, 6, 8], [11, 13, 5], [9, 9, 13]]


In [31]:
import numpy as np
a = np.array([[1,2,3],[3,4,5],[5,6,7]])
b = np.array([[3,4,5],[8,9,0],[4,3,6]])
c = np.add(a,b)
print(c)

[[ 4  6  8]
 [11 13  5]
 [ 9  9 13]]


# 5.	Write a Python program to check whether a given number is a narcissistic number or not
For example, 371 is a narcissistic number; it has three digits, and if we cube each digits  33 + 73 + 13 the sum is 371. Other 3-digit narcissistic numbers are
153 = 13 + 53 + 33


In [6]:
i = input("enter the no :")
no = int(i)
num = list(map(int,str(i)))
print(num)
count = len(num)
print(count)
sum = 0
for i in num:
    j = 1
    for k in range(count):
        j = j * i
    sum = sum+j
print(sum)
if no == sum:
    print("narcissists")
else:
    print("not narcissist")
    

enter the no :555
[5, 5, 5]
3
375
not narcissist
